"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("rooms/room");
require("prototypes");
const shed = require("shed");
const debug = require("debug");
require("logic/alllogic");
require("creep");
require("allcreeps");
require("roomobjs");
const allai_1 = require("ai/allai");
const spawners_1 = require("spawners");
global.findAI = allai_1.findAI;
const when = Game.time % 10;
function loop() {
    debug.log('version 1', when, require.timestamp % 10);
    const ais = _.map(Game.rooms, r => r.ai);
    shed.run(ais, 500, ai => ai.init());
    const logic = _.map(Game.flags, f => f.logic);
    const combats = _.filter(ais, ai => ai.hostiles.length > 0);
    shed.run(combats, 500, ai => ai.run());
    shed.run(combats, 1500, ai => ai.after());
    const claimed = _.filter(ais, ai => ai.room.controller && ai.room.controller.my && ai.hostiles.length === 0);
    shed.run(claimed, 2000, ai => ai.run());
    shed.run(claimed, 2000, ai => ai.after());
    const remotes = _.filter(ais, ai => ai.room.controller && !ai.room.controller.my && ai.hostiles.length === 0);
    shed.run(remotes, 3000, ai => ai.run());
    shed.run(remotes, 3000, ai => ai.after());
    const services = [spawners_1.run];
    shed.run(services, 4000, r => r());
    shed.run(combats, 6000, ai => ai.optional());
    shed.run(claimed, 7000, ai => ai.optional());
    shed.run(remotes, 8000, ai => ai.optional());
    shed.run(logic, 9000, team => team.darkRun());
}
exports.loop = loop;
